### PR TITLE
Genre entity

### PR DESCRIPTION
**Pull request by wo80**
Adds genre sub-query support to artist, release-group, release and recording entities.

### CODE REVIEW

**Comment by arsinclair** [comment]
Beautiful! Just came here to create an issue, cause I wasn't able to find it in your package, and the work on genres was carried out just 6 hours ago.☺

Just a small note: musicbrainz API in total provides four includes, that is: `tags`, `user-tags`, `genres`, `user-genres`, so the data contract will have to be extended to also accept `user-tags` and `user-genres`.

Maybe to be aligned with musicbrainz API there should be two separate collections, one for user-* specific tags and one for the accepted tags, however I think it will also make sense to have one collection that will accumulate all of them.

Great work overall!

**Comment by arsinclair** [comment]
I will be happy to see this merged soon. In fact, I was throwing away my own musicbrainz library because this one can do everything I need and good architected. And turns out, tags is the only thing that's blocking.

**Comment by wo80** [comment]
@arsinclair From my understanding, `user-tags` and `user-genres` will only be returned for authenticated users (i.e. will only return data, if the user has specficied tags/genres for the requested entity). Authentication isn't implemented, please open an issue if you need it.

I'm planing to release the updated nuget package this weekend.

**Comment by arsinclair** [comment]
> @arsinclair From my understanding, user-tags and user-genres will only be returned for authenticated users (i.e. will only return data, if the user has specficied tags/genres for the requested entity).

I just checked with the docs and you're actually right, it requires an authentication. I didn't know this data is not public.

Personally, I don't really need `user-tags` and `user-genres`, just _genres_ and _tags_, so I guess this can be put on hold.

Thank you.

**Pull request merged**
