### PR TITLE
Add support for retrieval of CoverArtUri

### PR DESCRIPTION
**Pull request by toolboc**

### CODE REVIEW

**Comment by toolboc** [comment]
@wo8, this allows for retrieval of the CoverArtUri in the response payload.  

It could be very useful if you are looking for associated cover art in a release query.

**Comment by wo80** [comment]
I don't think the uri is part of the response:

https://musicbrainz.org/ws/2/release/12195c41-6136-4dfd-acf1-9923dadc73e2

**Comment by toolboc** [comment]
Ahhh, now I remember why I needed this...

release.CoverArtArchive.CoverArtUri did not allow for databinding:
See: https://github.com/toolboc/Searchler/search?q=coverarturi&unscoped_q=coverarturi

Feel free to close if this is not needed.

**Comment by avatar29A** [comment]
Ok. Thanks for the PR anyway.

**Pull request closed without merging**
