### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by wo80**
Updating nuget packages and json test data.

Removing net45 target from main project, since .NET 4.5 is [no longer supported](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/).

@avatar29A Branch protection is set up so I can no longer directly push to master. I'm ok with that, but wanted to know if it is intended?

### CODE REVIEW

**Comment by wo80** [comment]
I'm wondering why Travis isn't running on this pull request/branch. Could you check whether there's an option that needs to be enabled?

**Comment by avatar29A** [comment]
@wo80 change settings, now should be ok.

Fastly, didnt see what wrong with travis. Check later again.

**Comment by wo80** [comment]
Thanks a bunch, @avatar29A ! I'll leave this pending for now, so you can test whether changing the Travis settings makes a difference here.

**Comment by avatar29A** [comment]
reconfigured travis. looks ok.

**Comment by wo80** [comment]
Yeah, looks good, thanks again!

Is the special `Travis` build configuration still needed or do you think this can be removed?

https://github.com/avatar29A/MusicBrainz/blob/c2798338393564b81c1295b5d554da30e595ab05/Hqub.MusicBrainz/Hqub.MusicBrainz.API/Hqub.MusicBrainz.API.csproj#L19-L21

**Comment by avatar29A** [comment]
Yes, I think it could be removed. Can we just test here?

**Comment by wo80** [comment]
Alright, CI seems to be working as it should. This should be ready to merge now.

**Pull request merged**
